### ISSUE TITLE
installation on linux fails b/c bin directory does not exist

### ISSUE THREAD

**Issue by abitofalchemy** [ehab-abdelhamid/GraMi#4]
Hello Ehab,  I forked your project, downloaded it, installed, but the install fails b/c the bin folder doesn't exist and I had to create it, I wasn't sure if this is by design or a minor issue.  I am interested in your work.  Specifically, I'm interested in not only learning what the most frequent subgraphs are, but print out the embeddings:  print the specific node #s & edges that countribute to the most FS.

**Comment by ehab-abdelhamid** [comment]
Hi,

Thanks for your interest in GraMi.
This is a known problem, it is a minor issue. We are going to fix it. What
you can do is to create this folder, and it will compile properly.

Specifically, I'm interested in not only learning what the most frequent
> subgraphs are, but print out the embeddings: print the specific node #s &
> edges that countribute to the most FS.


For GraMi, the idea is to return the set of frequent subgraphs. We do not
iterate over all embeddings, we only iterate over embeddings that
contribute the support threshold. For example, if support threshold = 100
and there are 1000 embeddings in the input graph, then we only iterate over
100 embeddings. If this is your case, then you can easily modify the code
so that it outputs the 100 embeddings.

Please let me know if you need further help.

Best regards,
Ehab

**Comment by abitofalchemy** [comment]
Hello Ehab,

I am grateful for the information.

The Datasets .lg file is as described by cs.rit.edu (Label Graph File
Format section in http://www.cs.rit.edu/~dprl/CROHMELib_LgEval_Doc.html#lg)

I will convert my .g file to .lg

Best regards,

**Comment by ehab-abdelhamid** [comment]
It is fixed now
